Charge game: LevelManager Class Reference
LevelManager Class Reference
Manages the levels in the game.
#include <levelManager.h>
Public Member Functions
const std::vector< std::string > & getLoadables () const
Get the list of loadable levels.
void updateIndex () const
Update the index of the levels.
Level loadLevel (const std::string &levelName) const
Load a level by its name.
Level loadLevel (const size_t &levelIndex) const
Load a level by its index.
Level loadLevel () const
Load a default level.
void saveLevel (const Level &level)
Save a level.
const bool deleteLevel (const std::string &levelName)
Delete a level by its name.
Static Public Member Functions
static LevelManager * getInstance ()
Get the instance of the LevelManager.
Detailed Description
Manages the levels in the game.
The LevelManager class is responsible for managing the levels in the game. It provides functionality to load, save, delete, and retrieve information about the levels.
Definition at line 15 of file levelManager.h.
Member Function Documentation
deleteLevel()
const bool LevelManager::deleteLevel (const std::string & levelName)
Delete a level by its name.
Parameters
levelName The name of the level to delete.
Returns
True if the level was successfully deleted, false otherwise.
Definition at line 215 of file levelManager.cpp.
{
    // Look for levelName in loadables with iterator
    // Auto because of complicated type name of iterators
    auto it = std::find(loadables.begin(), loadables.end(), levelName);
    // If end was reached without finding the level return false
    if (it == loadables.end())
    {
        return false;
    }
    // Remove levelName from loadables
    loadables.erase(it);
    // Delete the corresponding JSON file
    std::string filePath = "./levels/" + levelName + ".json";
    if (std::remove(filePath.c_str()) != 0) {
        throw std::runtime_error("LevelManager: Failed to delete level file: " + levelName + ".json");
    }
    return true;
}
getInstance()
LevelManager * LevelManager::getInstance () static
Get the instance of the LevelManager.
Returns
A pointer to the LevelManager instance.
Definition at line 16 of file levelManager.cpp.
{
    static LevelManager instance;
    return &instance;
}
getLoadables()
const std::vector< std::string > & LevelManager::getLoadables () const inline
Get the list of loadable levels.
Returns
A constant reference to the vector of loadable levels.
Definition at line 34 of file levelManager.h.
{ return loadables; }
loadLevel() [1/3]
Level LevelManager::loadLevel () const inline
Load a default level.
Returns
The loaded default Level object.
Definition at line 61 of file levelManager.h.
{ return Level(); }
loadLevel() [2/3]
Level LevelManager::loadLevel (const size_t & levelIndex) const
Load a level by its index.
Parameters
levelIndex The index of the level to load. 0 is always the oldest created level.
Returns
The loaded Level object.
Definition at line 155 of file levelManager.cpp.
{
    // Create level to be returned
    Level retLevel;
    // Catch errors occurring from overindexing, non-existent files etc...
    // Return empty level if error occured
    try
    {
        retLevel = loadLevel(loadables.at(levelIndex));
    }
    catch (const std::exception &e)
    {
        std::cerr << e.what() << '\n';
        return Level();
    }
    return retLevel;
}
References loadLevel().
loadLevel() [3/3]
Level LevelManager::loadLevel (const std::string & levelName) const
Load a level by its name.
Parameters
levelName The name of the level to load.
Returns
The loaded Level object.
Definition at line 104 of file levelManager.cpp.
{
    // Look for level to be loaded in loadables
    if (std::find(loadables.begin(), loadables.end(), levelName) != loadables.end())
    {
        // Try to open the json file
        std::ifstream levelFile("./levels/" + levelName + ".json");
        if (!levelFile)
            throw std::runtime_error("LevelManager: Level load error: " + levelName + ".json");
        // Deserialize it
        nlohmann::json jsonData;
        levelFile >> jsonData;
        // Read name, size, playerStartPos and fill obstacles
        std::string name = jsonData["name"];
        sf::Vector2u size(jsonData["size"]["x"], jsonData["size"]["y"]);
        // Create obstacles to be filled
        std::vector<std::shared_ptr<Obstacle>> obstacles;
        // Auto because type names are confusing with this library
        // Load fields of each obstacle into obstacle object
        for (const auto &obstacleData : jsonData["obstacles"])
        {
            // Load fields
            double charge = obstacleData["charge"];
            sf::Vector2f position(obstacleData["position"]["x"], obstacleData["position"]["y"]);
            double radius = obstacleData["radius"];
            // Construct obstacle object
            Obstacle obstacle(radius, charge, position);
            // Make shared pointer and push to obstacles
            obstacles.push_back(std::make_shared<Obstacle>(obstacle));
        }
        // Load playerstartpos
        sf::Vector2f playerStartPos(jsonData["playerStartPos"]["x"], jsonData["playerStartPos"]["y"]);
        // Construct level and return it
        return Level(levelName, size, obstacles, playerStartPos);
    }
    // If error occured throw runtime error
    else
    {
        throw std::runtime_error("LevelManager: Level not found: " + levelName + ".json");
    }
    if (debug == 5)
        std::cout << "Loaded level: " + levelName << std::endl;
}
saveLevel()
void LevelManager::saveLevel (const Level & level)
Save a level.
Parameters
level The Level object to save.
Definition at line 174 of file levelManager.cpp.
{
    // Open the file for writing
    std::ofstream levelFile("./levels/" + level.getName() + ".json");
    if (!levelFile)
        throw std::runtime_error("LevelManager: Level save error: " + level.getName() + ".json");
    // Write level data to json object
    nlohmann::json jsonData;
    jsonData["name"] = level.getName();
    jsonData["size"]["x"] = level.getSize().x;
    jsonData["size"]["y"] = level.getSize().y;
    jsonData["playerStartPos"]["x"] = level.getPlayerStartPos().x;
    jsonData["playerStartPos"]["y"] = level.getPlayerStartPos().y;
    // Create json objects for every obstacle
    for (const auto &obstacle : level.getObstacles())
    {
        nlohmann::json obstacleData;
        obstacleData["charge"] = obstacle.get()->getElectricCharge();
        obstacleData["position"]["x"] = obstacle.get()->getBody()->getPosition().x;
        obstacleData["position"]["y"] = obstacle.get()->getBody()->getPosition().y;
        obstacleData["radius"] = obstacle.get()->getBody()->getRadius();
        jsonData["obstacles"].push_back(obstacleData);
    }
    // Write to file
    levelFile << jsonData;
    // Add level name to loadables if it is not already present
    if (std::find(loadables.begin(), loadables.end(), level.getName()) == loadables.end())
        loadables.push_back(level.getName());
    if (debug == 5)
        std::cout << "Saved level: " + level.getName() << std::endl;
    levelFile.close();
}
References Level::getName(), Level::getObstacles(), Level::getPlayerStartPos(), and Level::getSize().
updateIndex()
void LevelManager::updateIndex () const
Update the index of the levels.
This function updates the index of the levels based on the current state of the game.
Definition at line 79 of file levelManager.cpp.
{
    // Open levels.txt for writing
    std::ofstream loadablesFile;
    loadablesFile.open("levels/index.txt");
    if (!loadablesFile)
    {
        if (debug == 5)
            std::cout << "Couldn't open index.txt for writing" << std::endl;
        return;
    }
    // Write loadables to the file, separated by newline
    for (const std::string &levelName : loadables)
    {
        loadablesFile << levelName << "\n";
        if (debug == 5)
            std::cout << "Loaded " + levelName + " to index.txt..." << std::endl;
    }
    loadablesFile.close();
    if (debug == 5)
        std::cout << "Finished saving index.txt" << std::endl;
}
The documentation for this class was generated from the following files:
levelManager.h
levelManager.cpp